services:
    tipc:
        image: tipc
        build:
            context: .
            dockerfile: Dockerfile
        privileged: true
        networks:
            - tipc_network
        volumes:
            - space:/space

networks:
    tipc_network:
        driver: bridge

volumes:
    space:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/space