services:
    node1:
        container_name: node1
        image: iptables
        build: .
        privileged: true
        networks:
            - network_a
    node2:
        container_name: node2
        image: iptables        
        privileged: true
        sysctls:
            net.ipv4.ip_forward: 1
        networks:
            - network_a
            - network_b
    node3:
        container_name: node3
        image: iptables
        privileged: true
        networks:
            - network_b

networks:
    network_a:
        driver: bridge
    network_b:
        driver: bridge
