services:
    iproute2:
        image: iproute2
        build: .
        privileged: true
        volumes:
            - "space:/space"

volumes:
    space:
        driver: local
        driver_opts:
            type: volume
            o: bind
            device: ~/space